[package]
name = "clingo-sys"
version = "0.1.0"
authors = ["sthiele <sthiele78@gmail.com>"]
description = "External FFI bindings to the C-API of the clingo library"
categories = ["external-ffi-bindings"]
build = "build.rs"
links = "clingo"
license = "GPL3"
repository = "https://github.com/sthiele/clingo-rs/clingo-sys"

[lib]
name = "clingo_sys"
path = "lib.rs"

[dependencies]
libc = "0.2.20"

[build-dependencies]
gcc = "0.3"
